name: deploy-user

on:
  push:
    branches:
      - master
    paths:
      - 'user/**'

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - run: cd user && docker build -t hetavshah/user .
       - run : docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
         env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       - run : docker push hetavshah/user
       - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
         with:
            service_account_key: ${{ secrets.GKE_SA_KEY }}
            project_id: ${{ secrets.GKE_PROJECT }}
